olist_ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host:     "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port:     "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname:   "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      user:     "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'changeme') }}"
      schema:   olist_dwh
      threads:  4
      connect_timeout: 10

    prod:
      type: postgres
      host:     "{{ env_var('POSTGRES_HOST') }}"
      port:     "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname:   "{{ env_var('POSTGRES_DB') }}"
      user:     "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      schema:   olist_dwh
      threads:  8
      connect_timeout: 30
